export const menuItems = [
  {
    type: "type",
    title: "组件总览",
    children: [
      {
        category: "Components",
        title: "组件总览",
        type: "组件总览",
        filename: "antLab/overview/index.zh-CN.md",
      },
    ],
    order: -1,
  },
  {
    type: "type",
    title: "通用",
    children: [
      {
        category: "Components",
        type: "通用",
        title: "At-Cus-Com",
        subtitle: "自定义组件",
        cover: "https://gw.alipayobjects.com/zos/alicdn/fNUKzY1sk/Button.svg",
        filename: "antLab/cuscom/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "通用",
        title: "At-Cus-Style",
        subtitle: "特殊样式",
        cover: "https://gw.alipayobjects.com/zos/alicdn/fNUKzY1sk/Button.svg",
        filename: "antLab/cusstyle/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "通用",
        title: "At-Cus-Ele",
        subtitle: "行内和块级元素",
        cover: "https://gw.alipayobjects.com/zos/alicdn/fNUKzY1sk/Button.svg",
        filename: "antLab/cusele/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "通用",
        title: "Button",
        subtitle: "按钮",
        cover: "https://gw.alipayobjects.com/zos/alicdn/fNUKzY1sk/Button.svg",
        filename: "antLab/button/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "图标",
        type: "通用",
        title: "Icon",
        toc: false,
        cover: "https://gw.alipayobjects.com/zos/alicdn/rrwbSt3FQ/Icon.svg",
        filename: "antLab/icon/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "排版",
        type: "通用",
        title: "Typography",
        cols: 1,
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/GOM1KQ24O/Typography.svg",
        filename: "antLab/typography/index.zh-CN.md",
      },
    ],
    order: 0,
  },
  {
    filename: "antLab/form/changelog.md",
  },
  {
    type: "type",
    title: "布局",
    children: [
      {
        category: "Components",
        type: "布局",
        title: "Divider",
        subtitle: "分割线",
        cover: "https://gw.alipayobjects.com/zos/alicdn/5swjECahe/Divider.svg",
        filename: "antLab/divider/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "栅格",
        type: "布局",
        cols: 1,
        title: "Grid",
        cover: "https://gw.alipayobjects.com/zos/alicdn/5rWLU27so/Grid.svg",
        filename: "antLab/grid/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "布局",
        type: "布局",
        cols: 1,
        title: "Layout",
        cover: "https://gw.alipayobjects.com/zos/alicdn/hzEndUVEx/Layout.svg",
        filename: "antLab/layout/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "布局",
        subtitle: "间距",
        title: "Space",
        cols: 1,
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/wc6%263gJ0Y8/Space.svg",
        filename: "antLab/space/index.zh-CN.md",
      },
    ],
    order: 1,
  },
  {
    type: "type",
    title: "导航",
    children: [
      {
        category: "Components",
        subtitle: "固钉",
        type: "导航",
        title: "Affix",
        cover: "https://gw.alipayobjects.com/zos/alicdn/tX6-md4H6/Affix.svg",
        filename: "antLab/affix/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "面包屑",
        type: "导航",
        title: "Breadcrumb",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/9Ltop8JwH/Breadcrumb.svg",
        filename: "antLab/breadcrumb/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "下拉菜单",
        type: "导航",
        title: "Dropdown",
        cover: "https://gw.alipayobjects.com/zos/alicdn/eedWN59yJ/Dropdown.svg",
        filename: "antLab/dropdown/index.zh-CN.md",
      },
      {
        category: "Components",
        cols: 1,
        type: "导航",
        title: "Menu",
        subtitle: "导航菜单",
        cover: "https://gw.alipayobjects.com/zos/alicdn/3XZcjGpvK/Menu.svg",
        filename: "antLab/menu/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "导航",
        title: "PageHeader",
        cols: 1,
        subtitle: "页头",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/6bKE0Cq0R/PageHeader.svg",
        filename: "antLab/page-header/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "分页",
        type: "导航",
        title: "Pagination",
        cols: 1,
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/1vqv2bj68/Pagination.svg",
        filename: "antLab/pagination/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "步骤条",
        type: "导航",
        cols: 1,
        title: "Steps",
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/UZYqMizXHaj/Steps.svg",
        filename: "antLab/steps/index.zh-CN.md",
      },
    ],
    order: 2,
  },
  {
    type: "type",
    title: "数据录入",
    children: [
      {
        category: "Components",
        subtitle: "自动完成",
        type: "数据录入",
        cols: 2,
        title: "AutoComplete",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/qtJm4yt45/AutoComplete.svg",
        filename: "antLab/auto-complete/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "数据录入",
        title: "Cascader",
        subtitle: "级联选择",
        cover: "https://gw.alipayobjects.com/zos/alicdn/UdS8y8xyZ/Cascader.svg",
        filename: "antLab/cascader/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "多选框",
        type: "数据录入",
        title: "Checkbox",
        cover: "https://gw.alipayobjects.com/zos/alicdn/8nbVbHEm_/CheckBox.svg",
        filename: "antLab/checkbox/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "数据录入",
        title: "DatePicker",
        subtitle: "日期选择框",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/RT_USzA48/DatePicker.svg",
        filename: "antLab/date-picker/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "表单",
        type: "数据录入",
        cols: 1,
        title: "Form",
        cover: "https://gw.alipayobjects.com/zos/alicdn/ORmcdeaoO/Form.svg",
        filename: "antLab/form/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "输入框",
        type: "数据录入",
        title: "Input",
        cover: "https://gw.alipayobjects.com/zos/alicdn/xS9YEJhfe/Input.svg",
        filename: "antLab/input/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "数字输入框",
        type: "数据录入",
        title: "InputNumber",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/XOS8qZ0kU/InputNumber.svg",
        filename: "antLab/input-number/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "提及",
        type: "数据录入",
        title: "Mentions",
        cover: "https://gw.alipayobjects.com/zos/alicdn/jPE-itMFM/Mentions.svg",
        filename: "antLab/mentions/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "单选框",
        type: "数据录入",
        title: "Radio",
        cover: "https://gw.alipayobjects.com/zos/alicdn/8cYb5seNB/Radio.svg",
        filename: "antLab/radio/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "评分",
        type: "数据录入",
        title: "Rate",
        cover: "https://gw.alipayobjects.com/zos/alicdn/R5uiIWmxe/Rate.svg",
        filename: "antLab/rate/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "选择器",
        type: "数据录入",
        title: "Select",
        cover: "https://gw.alipayobjects.com/zos/alicdn/_0XzgOis7/Select.svg",
        filename: "antLab/select/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "滑动输入条",
        type: "数据录入",
        title: "Slider",
        cover: "https://gw.alipayobjects.com/zos/alicdn/HZ3meFc6W/Silder.svg",
        filename: "antLab/slider/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "开关",
        type: "数据录入",
        title: "Switch",
        cover: "https://gw.alipayobjects.com/zos/alicdn/zNdJQMhfm/Switch.svg",
        filename: "antLab/switch/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "时间选择框",
        type: "数据录入",
        title: "TimePicker",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/h04Zsl98I/TimePicker.svg",
        filename: "antLab/time-picker/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "穿梭框",
        type: "数据录入",
        cols: 1,
        title: "Transfer",
        cover: "https://gw.alipayobjects.com/zos/alicdn/QAXskNI4G/Transfer.svg",
        filename: "antLab/transfer/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "树选择",
        type: "数据录入",
        title: "TreeSelect",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/Ax4DA0njr/TreeSelect.svg",
        filename: "antLab/tree-select/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "上传",
        type: "数据录入",
        title: "Upload",
        cover: "https://gw.alipayobjects.com/zos/alicdn/QaeBt_ZMg/Upload.svg",
        filename: "antLab/upload/index.zh-CN.md",
      },
    ],
    order: 3,
  },
  {
    type: "type",
    title: "数据展示",
    children: [
      {
        category: "Components",
        subtitle: "头像",
        type: "数据展示",
        title: "Avatar",
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/aBcnbw68hP/Avatar.svg",
        filename: "antLab/avatar/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "徽标数",
        type: "数据展示",
        title: "Badge",
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/6%26GF9WHwvY/Badge.svg",
        filename: "antLab/badge/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "数据展示",
        subtitle: "日历",
        cols: 1,
        title: "Calendar",
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/dPQmLq08DI/Calendar.svg",
        filename: "antLab/calendar/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "数据展示",
        title: "Card",
        subtitle: "卡片",
        cols: 1,
        cover: "https://gw.alipayobjects.com/zos/antfincdn/NqXt8DJhky/Card.svg",
        filename: "antLab/card/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "数据展示",
        title: "Carousel",
        subtitle: "走马灯",
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/%24C9tmj978R/Carousel.svg",
        filename: "antLab/carousel/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "数据展示",
        title: "Collapse",
        subtitle: "折叠面板",
        cols: 1,
        cover: "https://gw.alipayobjects.com/zos/alicdn/IxH16B9RD/Collapse.svg",
        filename: "antLab/collapse/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "数据展示",
        title: "Comment",
        subtitle: "评论",
        cols: 1,
        cover: "https://gw.alipayobjects.com/zos/alicdn/ILhxpGzBO/Comment.svg",
        filename: "antLab/comment/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "描述列表",
        type: "数据展示",
        title: "Descriptions",
        cols: 1,
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/MjtG9_FOI/Descriptions.svg",
        filename: "antLab/descriptions/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "空状态",
        type: "数据展示",
        title: "Empty",
        cols: 1,
        cover: "https://gw.alipayobjects.com/zos/alicdn/MNbKfLBVb/Empty.svg",
        filename: "antLab/empty/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "图片",
        type: "数据展示",
        title: "Image",
        cols: 2,
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/D1dXz9PZqa/image.svg",
        filename: "antLab/image/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "数据展示",
        title: "List",
        subtitle: "列表",
        cols: 1,
        cover: "https://gw.alipayobjects.com/zos/alicdn/5FrZKStG_/List.svg",
        filename: "antLab/list/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "气泡卡片",
        type: "数据展示",
        title: "Popover",
        cover: "https://gw.alipayobjects.com/zos/alicdn/1PNL1p_cO/Popover.svg",
        filename: "antLab/popover/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "统计数值",
        type: "数据展示",
        title: "Statistic",
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/rcBNhLBrKbE/Statistic.svg",
        filename: "antLab/statistic/index.zh-CN.md",
      },
      {
        category: "Components",
        cols: 1,
        type: "数据展示",
        title: "Table",
        subtitle: "表格",
        cover: "https://gw.alipayobjects.com/zos/alicdn/f-SbcX2Lx/Table.svg",
        filename: "antLab/table/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "标签页",
        type: "数据展示",
        title: "Tabs",
        cols: 1,
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/lkI2hNEDr2V/Tabs.svg",
        filename: "antLab/tabs/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "标签",
        type: "数据展示",
        title: "Tag",
        cover: "https://gw.alipayobjects.com/zos/alicdn/cH1BOLfxC/Tag.svg",
        filename: "antLab/tag/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "时间轴",
        type: "数据展示",
        title: "Timeline",
        cover:
          "https://gw.alipayobjects.com/zos/antfincdn/vJmo00mmgR/Timeline.svg",
        filename: "antLab/timeline/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "文字提示",
        type: "数据展示",
        title: "Tooltip",
        cover: "https://gw.alipayobjects.com/zos/alicdn/Vyyeu8jq2/Tooltp.svg",
        filename: "antLab/tooltip/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "数据展示",
        title: "Tree",
        subtitle: "树形控件",
        cover: "https://gw.alipayobjects.com/zos/alicdn/Xh-oWqg9k/Tree.svg",
        filename: "antLab/tree/index.zh-CN.md",
      },
    ],
    order: 4,
  },
  {
    type: "type",
    title: "反馈",
    children: [
      {
        category: "Components",
        subtitle: "警告提示",
        type: "反馈",
        title: "Alert",
        cover: "https://gw.alipayobjects.com/zos/alicdn/8emPa3fjl/Alert.svg",
        filename: "antLab/alert/index.zh-CN.md",
      },
      {
        type: "反馈",
        category: "Components",
        subtitle: "抽屉",
        title: "Drawer",
        cover: "https://gw.alipayobjects.com/zos/alicdn/7z8NJQhFb/Drawer.svg",
        filename: "antLab/drawer/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "全局提示",
        type: "反馈",
        noinstant: true,
        title: "Message",
        cover: "https://gw.alipayobjects.com/zos/alicdn/hAkKTIW0K/Message.svg",
        filename: "antLab/message/index.zh-CN.md",
      },
      {
        type: "反馈",
        category: "Components",
        subtitle: "对话框",
        title: "Modal",
        cover: "https://gw.alipayobjects.com/zos/alicdn/3StSdUlSH/Modal.svg",
        filename: "antLab/modal/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "反馈",
        noinstant: true,
        title: "Notification",
        subtitle: "通知提醒框",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/Jxm5nw61w/Notification.svg",
        filename: "antLab/notification/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "气泡确认框",
        type: "反馈",
        title: "Popconfirm",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/fjMCD9xRq/Popconfirm.svg",
        filename: "antLab/popconfirm/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "进度条",
        type: "反馈",
        title: "Progress",
        cover: "https://gw.alipayobjects.com/zos/alicdn/xqsDu4ZyR/Progress.svg",
        filename: "antLab/progress/index.zh-CN.md",
      },
      {
        type: "反馈",
        category: "Components",
        title: "Result",
        cols: 1,
        subtitle: "结果",
        cover: "https://gw.alipayobjects.com/zos/alicdn/9nepwjaLa/Result.svg",
        filename: "antLab/result/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "骨架屏",
        type: "反馈",
        title: "Skeleton",
        cols: 1,
        cover: "https://gw.alipayobjects.com/zos/alicdn/KpcciCJgv/Skeleton.svg",
        filename: "antLab/skeleton/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "反馈",
        title: "Spin",
        subtitle: "加载中",
        cover: "https://gw.alipayobjects.com/zos/alicdn/LBcJqCPRv/Spin.svg",
        filename: "antLab/spin/index.zh-CN.md",
      },
    ],
    order: 5,
  },
  {
    type: "type",
    title: "其他",
    children: [
      {
        category: "Components",
        subtitle: "锚点",
        cols: 2,
        type: "其他",
        title: "Anchor",
        cover: "https://gw.alipayobjects.com/zos/alicdn/_1-C1JwsC/Anchor.svg",
        filename: "antLab/anchor/index.zh-CN.md",
      },
      {
        category: "Components",
        type: "其他",
        subtitle: "回到顶部",
        title: "BackTop",
        cover: "https://gw.alipayobjects.com/zos/alicdn/tJZ5jbTwX/BackTop.svg",
        filename: "antLab/back-top/index.zh-CN.md",
      },
      {
        category: "Components",
        subtitle: "全局化配置",
        cols: 1,
        type: "其他",
        title: "ConfigProvider",
        cover:
          "https://gw.alipayobjects.com/zos/alicdn/kegYxl1wj/ConfigProvider.svg",
        filename: "antLab/config-provider/index.zh-CN.md",
      },
    ],
    order: 6,
  },
];
